### ISSUE TITLE
Enable metadata for Zenodo

### ISSUE THREAD

**Issue by aelligp** [PTsolvers/JustRelax.jl#70]
Zenodo allows to define a `.zenodo.json` in a repo where one can define the meta data that will show up in the Zenodod release.

This would allow to avoid having to manually edit entries in Zenodo once the release done and also add the possibility to directly include funding information (e.g. ERC, PASC, EuroHPC).

Zenodo doc on how to proceed: https://developers.zenodo.org/#add-metadata-to-your-github-repository-release

**Comment by luraess** [comment]
Thanks for digging out this resource @aelligp ! One could try dating such file, and checking if things work in an upcoming release.

**Comment by boriskaus** [comment]
ok, so it looks like this is the info required by zenodo. Fine this by clicking on the Zenodo link and `export to JSON`
```
    "funding": [
      {
        "award": {
          "acronym": "MAGMA",
          "id": "00k4n6c32::771143",
          "identifiers": [
            {
              "identifier": "https://cordis.europa.eu/projects/771143",
              "scheme": "url"
            }
          ],
          "number": "771143",
          "program": "H2020",
          "title": {
            "en": "Melting And Geodynamic Models of Ascent"
          }
        },
        "funder": {
          "id": "00k4n6c32",
          "name": "European Commission"
        }
      }
```

**Comment by luraess** [comment]
> we should obviously also as the PASC project, but I don't have the numbers

Well, I guess PASC is not listed outside of ETH. SO we could come up with some manual entry filling, but would not know the relating IDs...

**Comment by luraess** [comment]
Also, I guess one could add Contributors info as names, ORCID, and affiliations are always messed up in Zenodo

**Comment by luraess** [comment]
An attempt is done in #69
